config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    collection do
      get"home"
      get"ajaxshow"
      
      get"showmeeting"
    end
  end
  resources :guests do 
    collection do
      get"meeting"
    end
  end
  root"users#index"

  resources :mettings do 
    collection do
      get"notification"
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :role
  validates :phone, uniqueness: true

  has_many :mettings ,dependent: :destroy
  accepts_nested_attributes_for :mettings 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: [:new, :create]

  def home 
    @user = User.find_by(id: session[:user_id]) 
    @activeuser = User.find_by(id: session[:user_id]) 
    @date=Time.now;
    @active="home"
  end
  
  def index
    @userall =User.all
    @user = User.find_by(id: session[:user_id])   
    @role=Role.all
    @active="index"
  end

  def showmeeting
   @active = "show"
    @user = User.find_by(id: session[:user_id])   
    @usermeet=@user.mettings.all.order("created_at DESC")
    # render json:{usermeet: @usermeet}
  end

  def ajaxshow
    @user = User.find_by(id: session[:user_id])   
    @usermeet=@user.mettings.all
    render json:{usermeet: @usermeet}
    
  end

  # def notification
  #   @mettingall = Metting.all
  #   render json:{meet: @mettingall}
  # end

  def show
    @active="profile"
    @user = User.find_by(id: session[:user_id])
    @userindex= User.find_by(id: params[:id])
  end

  def new
    @active="index"
    @user = User.find_by(id: session[:user_id])
    @usernew= User.new
  end

  def create
    @usernew = User.create(user_params)
    respond_to do |format|
      if @usernew.save
        format.html { redirect_to users_path }
        flash[:notice] = "Employee Created Successfully"
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @active="profile"
    
  end

  def update
   
    respond_to do |format|
      if @user.update(user_params)
        flash[:notice] = "Employee Updated Successfully"
        format.html { redirect_to user_path(@user) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to users_path  
  end

  private
  
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :address, :password, :role_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.select(:role_id, options_for_select([['Employee','2'],['Admin','1'],['Receptionist','3']]),{include_blank: true}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div style="width:100%;height:55px" class="bbottom">
    <div><h1>PROFILE<span style="font-size:16px;">
      <% if @user.role.id == 1 || @user.role.id == 2 %>
        <ul class="navbar-nav float-right">
         <div class="dropdown" style="float:right;">
          <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count1"></span>
          </a>
          <div class="dropdown-content" id="shownotification1" >
            <a href="#">No New Notification</a>
          </div>
        </div>
        </ul></span></h1>
        <% else %>
        <ul class="navbar-nav float-right" style="display:inline-block-block">
          <!-- Notifications Dropdown Menu -->
          <span style="font-size:16px;">
            <ul class="navbar-nav float-right">
             <div class="dropdown" style="float:right;">
              <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count2"></span>
              </a>
              <div class="dropdown-content" id="shownotification2" >
                <a href="#">No New Notification</a>
              </div>
            </div>
            </ul></span>
          </h1>
      <% end %>
    </div>
  </div>

  
  
  <div class="row ">
    <div class="col-md-3">
    </div>
      <div style="width:600px;background-color:rgb(221, 213, 213)"class="col-md-5 py-3 px-3 mt-4">
        <%= form_for @user do |form| %>
          <h2 class="text-center">Edit Profile</h2>
            <div class="field">
              <%= form.label :name %>:
              <%= form.text_field :name,class:"form-control" ,required:"true"%>
            </div>
          
            <div class="field">
              <%= form.label :email %>:
              <%= form.text_field :email,class:"form-control",pattern:"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$",placeholder:"your@email.com"%>
            </div>
          
            <div class="field">
              <%= form.label :phone %>:
              <%= form.text_field :phone,class:"form-control",required:"true",minlength: 10, maxlength: 10,pattern:"[0-9]{10}"  %>
            </div>
          
            <div class="field">
              <%= form.label :address %>:
              <%= form.text_area :address,class:"form-control" %>
            </div>
          
            <div class="field">
              <%= form.label :password %>:
              <%= form.text_field :password,class:"form-control",placeholder:"Leave blank if dont want to change"%>
            </div>
            <% if @user.role.id == 5%>
            <div class="field">
              <%= form.label :role_id %>:
              <%= form.select(:role_id, options_for_select([['Employee','2'],['Admin','1'],['Receptionist','3']]),{include_blank: true},class:"form-control")%>
            </div>
            <% end %>
          
            <div class="actions mt-2 text-center">
              <%= form.submit class:"btn btn-dark"%>
            </div>
          <% end %>
        </div>
    
      </div>
    </div>
</div>
</body>

app/views/users/home.html.erb
<div class="container">
  <div style="width:100%;height:55px" class="bbottom">
    <div><h1>HOME<span style="font-size:16px;">
      <% if @user.role.id == 1 || @user.role.id == 2 %>
        <ul class="navbar-nav float-right">
         <div class="dropdown" style="float:right;">
          <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count1"></span>
          </a>
          <div class="dropdown-content" id="shownotification1" >
            <a href="#">No New Notification</a>
          </div>
        </div>
        </ul></span></h1>

        <% else %>
        <span style="font-size:16px;">
          <ul class="navbar-nav float-right">
           <div class="dropdown" style="float:right;">
            <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count2"></span>
            </a>
            <div class="dropdown-content" id="shownotification2" >
              <a href="#">No New Notification</a>
            </div>
          </div>
          </ul></span>
        </h1>

      <% end %>
    </div>
  </div>
  <br>
<div class="container">
  <div class="jumbotron ">
  <h1>Hi,<%= @user.name.to_s.split(" ")[0].capitalize%></h1>
      <h1 class="display-5 ml-3">Welcome To Guest Management</h1>
      <%= link_to "Sign out", session_path(@user.id), method:"delete" ,class:"btn btn-info"%>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div style="width:100%;height:55px" class="bbottom">
  <div><h1>EMPLOYEES<span style="font-size:16px;">
  <% if @user.role.id == 1 || @user.role.id == 2 %>
    <ul class="navbar-nav float-right">
     <div class="dropdown" style="float:right;">
      <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count1"></span>
      </a>
      <div class="dropdown-content" id="shownotification1" >
        <a href="#">No New Notification</a>
      </div>
    </div>
    </ul></span></h1>
    <% end %>
  </div>
</div>
<div class="container mt-2">
  <% if flash[:notice] %>
    <div class="text-center container">
        <div class="alert alert-warning alert-dismissible" role="alert">
            <strong><%=flash[:notice] %></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
  <% end %>
</div>
<div class="container mt-2">
<table class="table table-secondary table-striped table-bordered">
  <thead class="bg-success">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <% if @user.role.id == 1%>
      <th colspan="3">Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @userall.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>      
        <td><%= user.role.role %></td>
        <% if @user.role.id == 1%>
          <td><%= link_to 'Show', user,class:"btn btn-success" %></td>
          <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-primary" %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @user.role.id == 1%>
  <%= link_to 'Add Employee', new_user_path ,class:"btn btn-dark"%>
<% end %>
</div>
<br>
</div>

app/views/users/new.html.erb
<div class="container ">
  <div style="width:100%;height:55px" class="bbottom">
    <div><h1>PROFILE<span style="font-size:16px;">
      <% if @user.role.id == 1 || @user.role.id == 2 %>
        <ul class="navbar-nav float-right">
         <div class="dropdown" style="float:right;">
          <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count1"></span>
          </a>
          <div class="dropdown-content" id="shownotification1" >
            <a href="#">No New Notification</a>
          </div>
        </div>
        </ul></span></h1>
      <% end %>
    </div>
  

<br>
<div class="row">
  <div class="col-md-3">
  </div>
    <div style="width:400px;background-color:rgb(218, 214, 214)"class="col-md-5 py-3 px-3">
      <%= form_for @usernew do |form| %>
        <h2 class="text-center">Add Employee</h2>
          <div class="field">
            <%= form.label :name %>:
            <%= form.text_field :name,class:"form-control",required:"true" %>
          </div>
        
          <div class="field">
            <%= form.label :email %>:
            <%= form.email_field :email,class:"form-control",required:"true",placeholder:"email@mail.com" %>
          </div>
        
          <div class="field">
            <%= form.label :phone %>:
            <%= form.text_field :phone,class:"form-control" ,required:"true" ,minlength: 10, maxlength: 10,pattern:"[0-9]{10}"  %>
          </div>
        
          <div class="field">
            <%= form.label :address %>:
            <%= form.text_area :address,class:"form-control",required:"true" %>
          </div>
        
          <div class="field">
            <%= form.label :password %>:
            <%= form.text_field :password,class:"form-control",required:"true" %>
          </div>
        
          <div class="field">
            <%= form.label :role_id %>:
            <%= form.select(:role_id, options_for_select([['Employee','2'],['Admin','1'],['Receptionist','3']]), {:prompt => '--select--'},class:"form-control")%>
          </div>
        
          <div class="actions text-center mt-2">
            <%= form.submit class:"btn btn-dark"%>
          </div>
        <% end %>
      </div>
  
    </div>
  </div>
</body>

app/views/users/show.html.erb
<div class="container ">
  <div style="width:100%;height:55px" class="bbottom">
    <div><h1>PROFILE<span style="font-size:16px;">
    <% if @user.role.id == 1 || @user.role.id == 2 %>
      <ul class="navbar-nav float-right">
       <div class="dropdown" style="float:right;">
        <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count1"></span>
        </a>
        <div class="dropdown-content" id="shownotification1" >
          <a href="#">No New Notification</a>
        </div>
      </div>
      </ul></span></h1>
        <% else %>
        <span style="font-size:16px;">
              <ul class="navbar-nav float-right">
               <div class="dropdown" style="float:right;">
                <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><span class="badge badge-danger" style="font-size:15px;"id="count2"></span>
                </a>
                <div class="dropdown-content" id="shownotification2" >
                  <a href="#">No New Notification</a>
                </div>
              </div>
              </ul></span>
            </h1>

      <% end %>
    </div>
  </div>

<div class="container mt-2">
<% if flash[:notice] %>
    <div class="text-center container">
        <div class="alert alert-warning alert-dismissible" role="alert">
            <strong><%=flash[:notice] %></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
  <% end %>

</div>
<div class="container mt-3">
<div class="jumbotron container py-3">
 
    <h1>
    <strong><%= @userindex.name %></strong>
    </h1>
  <hr>
    <p>
    <strong>Email:</strong>
    <%= @userindex.email %>
    </p>

    <p>
    <strong>Phone:</strong>
    <%= @userindex.phone %>
    </p>

    <p>
    <strong>Address:</strong>
    <%= @userindex.address %>
    </p>

    <p>
    <strong>Role:</strong>
    <%= @userindex.role.role%>
    </p>
    <% if @user == @userindex %>
    <%= link_to "Edit ", edit_user_path,class:"btn btn-dark mx-1" %> 
    <% end %>   
   
    
</div>
</div>

app/views/users/showmeeting.html.erb
  <div class="container">
    <div style="width:100%;height:55px" class="bbottom ">
      <div><h1>MEETINGS<span style="font-size:16px;">
        <% if @user.role.id == 1 || @user.role.id == 2 %>
          <ul class="navbar-nav float-right">
           <div class="dropdown" style="float:right;">
            <a class="btn mr-5 " href="#" role="button" id="notificationadmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class=" fa fa-bell fa-2x"></i><span class=" p-1" ><sup class="badge badge-danger" style="font-size:15px;"id="count1"></sup>
            </a>
            <div class="dropdown-content" id="shownotification1" >
              <a href="#">No New Notification</a>
            </div>
          </div>
          </ul></span></h1>
        <% end %>
      </div>
    </div>
    
    
    <div class="container">
  <% @usermeet.each do |meet| %>
      
        <% if meet.status == "4" %>
          <div class="container mt-3">
            <div class="jumbotron jumbotron-fluid py-4" style="border:5px solid black;border-radius: 10px;">
              <div class="container py-0">
            
                <h1 class=""><%= meet.guest.name %></h1>
                <p class="lead">
                  
                  <div class="mx-3 ">
                    <h5><strong>Purpose:</strong>
                    <%= meet.purpose %></h5>
                    <h5>Prescheduled at :- <%= meet.reschedule.to_time.strftime('%B %e at %l:%M %p') %></h5>
                  </div>
              </div>
            </div>
          </div>

        <% end %>      
              
        <% if meet.status == "0" %>
        
        <div class="container mt-3">
          <div class="jumbotron jumbotron-fluid py-4" style="border:5px solid black;border-radius: 10px;">
          <div class="container py-0">
        
            <h1 class=""><%= meet.guest.name %></h1>
            <p class="lead">
              
              <div class="mx-3 ">
                <h5><strong>Purpose:</strong>
                <%= meet.purpose %></h5>
              </div>
              
              
              <div>  
                <!-- Accept -->
              <%= form_for meet,style:"float: left; padding: 5px;" do |form| %>
              <%= form.hidden_field:status ,value:"1",style:"display:inline-block" %>
              <%= form.submit "Accept",class:"btn btn-success",style:"float: left; margin-left: 28%;margin-right:30px" %>
              <% end %>   
              <!-- Reject -->
              
              <span> <button type="button" class="btn btn-danger mx-4" data-toggle="modal" data-target="#exampleModal1">Reject</button></span>
              <span> <button type="button" class="btn btn-primary mx-4" data-toggle="modal" data-target="#exampleModal">Reschedule</button></span>
          
      
              </div>
              <!-- Reschedule Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Reschedule</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= form_for meet do |form| %>
                      <%= form.datetime_field :reschedule, class:"form-control" ,:required => true %>
                      <br>
                      <%= form.text_field:reason , required:"true" ,placeholder:"reason" ,class:"form-control" %>
                      
                      <%= form.text_field :status ,value:"3",hidden:"true", :required => true  %>
                      <br>
                      <div class="text-center">
                      <%= form.submit "Reschedule", class:"btn btn-primary ml-4"%>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Reject Modal2 -->
              <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel1">Reject</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= form_for meet ,style:"" do |form| %>
                      <%= form.hidden_field:status ,value:"2" %>
                      <%= form.text_field:reason , required:"true" ,placeholder:"reason"%>
                      <%= form.submit "Reject",class:"btn btn-danger" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </p>
        </div>
      </div>
     
        <% end %>
<% end %>
      
</div>