config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    collection do
      get"home"
      get"ajaxshow"
      
      get"showmeeting"
    end
  end
  resources :guests do 
    collection do
      get"meeting"
    end
  end
  root"users#index"

  resources :mettings do 
    collection do
      get"notification"
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #28a745;
  overflow-x: hidden;
  padding-top: 30px;
  border-right: 3px solid black;
}

.sidenav a {
  text-decoration: none;
  font-size: 25px;
  color: black;
  display: block;
}

.sidenav a:hover {
  background-color: rgb(0, 0, 0);
  color:white;
  margin-left: 8px;
  transition: 0.6s;
  transition-delay: 0.07s;
  font-size:30px;
}




@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
.active a{
  background-color: black;
  color: white !important;
  margin-left: 8px;
}
</style>
</head>
<body>

<div class="sidenav wid-20">
  
   <h4 class="mb-3 text-center"><b>Guest Management</b></h4>
   
    <div class="<%= 'active' if @active=="home" %>" >
      <%= link_to home_users_path,class:"px-5 py-3 "  do%>
      <h5><i class="fa fa-home " aria-hidden="true"></i> HOME</h5>
      <% end %>
    </div>
    <div class="<%= 'active' if @active=="meeting" %>" >
    <%= link_to meeting_guests_path,class:"px-5 py-3" do%>
      <h5><i class="fa fa-address-card-o" aria-hidden="true"></i> ADD MEETING</h5>
    <% end %>
  </div>
      <% if @user.role.id == 3 || @user.role.id == 1%>
     
    <% else %>
    <div class="<%= 'active' if @active=="show" %>" >
      <%= link_to showmeeting_users_path ,class:"px-5 py-3" do%>
        <h5><i class="fa fa-commenting" aria-hidden="true"></i> MEETINGS</h5>
      <% end %>
    </div>
    <% end %>
    <div class="<%= 'active' if @active=="index" %>" >
    <% if @user.role.id == 1%>
    <%= link_to  users_path,method:"get",class:"px-5 py-3" do%>
      <h5><i class="fa fa-users" aria-hidden="true"></i> EMPLOYEES</h5>
    <% end %>
    <% end %>
    </div>
    <% if @user.role.id == 3 || @user.role.id == 1%>
    <div class="<%= 'active' if @active=="all" %>" >
    <%= link_to mettings_path,class:"px-5 py-3" do%>
     <h5> <i class="fa fa-list" aria-hidden="true"></i> ALL MEETINGS </h5>
      <% end %>
      </div>
      <% end %>
    <div class="<%= 'active' if @active=="profile" %>" >
    <%= link_to user_path(@user.id),class:"px-5 py-3" do%>
      <h5><i class="fa fa-user" aria-hidden="true"></i> PROFILE</h5>
    <% end %>
    </div>

    <%= link_to  session_path(@user.id), method:"delete",class:"px-5 py-3 " do %>
      <h5><i class="fa fa-power-off" aria-hidden="true"></i> SIGN OUT</h5>
    <% end %>
   
</div>   
</body>
</html> 










    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guest-Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>  
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
   <style>
      body{
        overflow-x:hidden;
      }
      .wid-20{
        min-width: 20%;
      }
      .wid-80{
        min-width: 80%;
      }
          .bbottom{
        border-bottom:2px solid grey;
      }
        .dropbtn {
        background-color: #04AA6D;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
      }

      .dropdown {
        position: relative;
        display: inline-block;
      }

      .dropdown-content {
        display: none;
        position: absolute;
        right: 0;
        background-color: #f9f9f9;
        min-width: 200px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
      }

      .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
      }
      .dropdown:hover .dropdown-content {display: block;}

    </style>
  </head>

  <body style="font-family:poppins;">
  <div class="row">
    <% if logged_in? %>
   
      <div class="wid-20">
        <%= render 'layouts/navbar'%>
    </div>
    <% end %>
      <div class="wid-80">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        <%= yield %>
      </div>
  </div>

<script>
  setInterval(reload,5000);
  function reload(){
    // console.log("hello");
    $.ajax({
      type: "get",
      url: "http://localhost:3000/users/ajaxshow",
      dataType: "json",
      success:function(usermeet){
       var arr;
       var count=0;
       console.log(usermeet);
       usermeet['usermeet'].forEach(user => {
         if (user['status'] == "0")
         {
          // arr=arr+'<a class="dropdown-item" href="/users/showmeeting">'+ user['guest_id']+ ' wants to meet</a>'    
         
         count=count+1;
        }
        arr= '<a class="dropdown-item" href="/users/showmeeting">You have a new meeting</a>';
       });                                                  

        console.log(count);
        if (count>0){
          $('#count1').html(count);    
          $('#shownotification1').html(arr);
        }
      }
    })
    $.ajax({
      type: "get",
      url: " http://localhost:3000/mettings/notification",
      dataType: "json",
      success:function(meet){
       var arr;
       var arr1=[];
       var arr2=[];
       var arr3=[];
       var arr4=[];
       var count=0; 
       var count1=0;
       var count2=0;
       var count3=0;
       var count4=0;
       console.log(meet);
       meet['meet'].forEach(user => {
        if (user['status'] == "1" ||user['status'] == "2" ||user['status'] == "3" ||user['status'] == "4"  )
         {
            if(user['status'] == "1"){
                count1=count1+1;
                arr1=arr1+'<a class="dropdown-item" href="/mettings">'+user['name']+' has Accepted'
                  console.log(user['name']);
            }
            if(user['status'] == "2"){
              arr2=arr2+'<a class="dropdown-item" href="/mettings">'+user['name']+' has Rejected'
            }
            if(user['status'] == "3"){
                count3=count3+1;
                arr3=arr3+'<a class="dropdown-item" href="/mettings">'+user['name']+' has Rescheduled'
            }
            if(user['status'] == "4"){
                count4=count4+1;
                arr4=arr4+'<a class="dropdown-item" href="/mettings">'+user['name']+' has Prescheduled'
            
            }
            
            count=count+1;
          
         }
        //  arr1=['<a class="dropdown-item" href="/mettings">'+ count1+' Aceepted</a>','<a class="dropdown-item" href="/mettings"> '+count2+' Rejected</a>','<a class="dropdown-item" href="/mettings">'+ count3+' Rescheduled</a>'];
        arr= '<a class="dropdown-item" href="/mettings">New Notification</a>';
        
       });                                                  

        // console.log(count);
        if (count>0){
          $('#count2').html(count);    
          $('#shownotification2').html(arr1+'\n'+arr2+"\n"+arr3+"\n"+arr4);
        }
      }
    })
    // document.getElementsById("count2").hide()
  }
  </script>
  </body>
</html>